language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

services:
  - mongodb

# Cache pip dependencies to speed up builds
cache: pip

# Install dependencies
before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt
  # Install testing and analysis tools
  - pip install pytest pytest-cov pylint flake8 mypy

# Set environment variables for testing
env:
  global:
    - MONGO_URI=mongodb://localhost:27017/
    - PLANS_DIRECTORY=lesson_plans
    - SAVE_TO_MONGODB=true
    - SAVE_TO_FILE=true
    - ENABLE_COMPARER=false
    - PYTHONPATH=$PYTHONPATH:$(pwd)

# Run tests and analysis
script:
  # Static type checking
  - mypy --ignore-missing-imports .

  # Style checking
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --statistics

  # Run unit tests with coverage
  - pytest --cov=./ --cov-report=xml --cov-report=term-missing

  # Run linting
  - pylint --disable=R,C,W1203,W0703 *.py

# After success actions
after_success:
  # Upload coverage to Codecov
  - bash <(curl -s https://codecov.io/bash)

# Notifications
notifications:
  email:
    on_success: change
    on_failure: always
