name: Check Environment Variables

on:
  pull_request:
    branches: [ secondyear, dev, staging ]
  push:
    branches: [ secondyear, dev, staging ]
  workflow_dispatch:

jobs:
  check-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check required environment variables
        run: |
          required_vars=(
            "REGISTRY_URL"
            "REGISTRY_USERNAME"
            "REGISTRY_PASSWORD"
            "EMAIL"
            "SENTRY_DSN"
            "PASSWORD"
            "OPENROUTER_API_KEY"
            "SELECTED_MODEL"
            "DISCORD_WEBHOOK_URL"
            "MONGO_URI"
            "WERKZEUG_RUN_MAIN"
            "ENABLE_COMPARER"
            "MONGO_DB"
          )
          
          missing_vars=()
          empty_vars=()
          
          for var in "${required_vars[@]}"; do
            # Sprawdź czy zmienna istnieje w secrets
            if [ -z "${{ secrets[var] }}" ]; then
              if [ ! -z "${{ secrets[var] }}" ]; then
                empty_vars+=("$var")
              else
                missing_vars+=("$var")
              fi
            fi
          done
          
          # Wyświetl brakujące zmienne
          if [ ${#missing_vars[@]} -ne 0 ]; then
            echo "❌ Missing required secrets:"
            printf '%s\n' "${missing_vars[@]}"
            exit 1
          fi
          
          # Wyświetl puste zmienne
          if [ ${#empty_vars[@]} -ne 0 ]; then
            echo "❌ Following secrets are empty:"
            printf '%s\n' "${empty_vars[@]}"
            exit 1
          fi
          
          echo "✅ All required environment variables are properly set!"